"""Typed event bus CORE (Qt-free).

Defines the single typed publish/subscribe channel every cross-component,
cross-thread message in the application travels on: the ``EventBus`` and
``Subscription`` Protocols (``docs/v3_specification/08_Cross_Cutting/08-E_interfaces_contracts.md``
§6), the closed set of 33 signal-name constants, and every event payload
``msgspec.Struct`` in the catalogue
(``docs/v3_specification/08_Cross_Cutting/08-J_event_bus_catalog.md`` §7;
``docs/v3_specification/08_Cross_Cutting/08-Q_event_payload_schemas.md``).

This module defines the Protocols, the constants, and the payload types only —
no concrete ``EventBus`` implementation, no Qt delivery bridge, and no emitter or
subscriber logic. The concrete implementation and its Qt bridge live in
``adapters/qt_event_bus/`` (a later story).
"""

from ollama_llm_bench.backend.events.models import (
    SIGNAL_APP_READINESS_CHANGED,
    SIGNAL_APP_SETTINGS_CHANGED,
    SIGNAL_CHART_DATA_CHANGED,
    SIGNAL_DETAILED_DATA_CHANGED,
    SIGNAL_GLOBAL_MESSAGE,
    SIGNAL_INFERENCE_ACTIVITY_CHANGED,
    SIGNAL_INFERENCE_COMPLETED,
    SIGNAL_INFERENCE_PROGRESS,
    SIGNAL_INFERENCE_STARTED,
    SIGNAL_JUDGE_COMPLETED,
    SIGNAL_JUDGE_MODEL_EXCLUDED,
    SIGNAL_JUDGE_STARTED,
    SIGNAL_LOG_CLEARED,
    SIGNAL_MODEL_STABILITY_CHANGED,
    SIGNAL_MODEL_SWITCHED,
    SIGNAL_PROGRESS_UPDATED,
    SIGNAL_PROVIDER_INFERENCE_TEST_COMPLETED,
    SIGNAL_PROVIDER_REGISTRY_RELOADED,
    SIGNAL_PROVIDER_SWITCHED,
    SIGNAL_RUN_ANALYSIS_RECEIVED,
    SIGNAL_RUN_FAILED,
    SIGNAL_RUN_FINISHED,
    SIGNAL_RUN_ID_CHANGED,
    SIGNAL_RUN_LIST_CHANGED,
    SIGNAL_RUN_PAUSED,
    SIGNAL_RUN_RENAMED,
    SIGNAL_RUN_RESUMED,
    SIGNAL_RUN_START_FAILED,
    SIGNAL_RUN_STARTED,
    SIGNAL_RUN_STOPPED,
    SIGNAL_STAGE_CHANGED,
    SIGNAL_SUMMARY_DATA_CHANGED,
    SIGNAL_TASK_COMPLETED,
    SIGNAL_TASK_FILE_CHANGED,
    SIGNAL_TASK_RETRY,
    SIGNAL_WORKSPACE_CHANGED,
    AppReadinessChangedEvent,
    AppSettingsChangedEvent,
    ChartDataChangedEvent,
    DetailedDataChangedEvent,
    GlobalMessageEvent,
    InferenceActivityChangedEvent,
    InferenceCompletedEvent,
    InferenceProgressEvent,
    InferenceStartedEvent,
    InferenceTestCompletedEvent,
    JudgeCompletedEvent,
    JudgeModelExcludedEvent,
    JudgeStartedEvent,
    LogClearedEvent,
    ModelStabilityChangedEvent,
    ModelSwitchedEvent,
    ProgressUpdatedEvent,
    ProviderHealthSummary,
    ProviderRegistryReloadedEvent,
    ProviderSwitchedEvent,
    RunAnalysisReceivedEvent,
    RunFailedEvent,
    RunFinishedEvent,
    RunIdChangedEvent,
    RunListChangedEvent,
    RunListEntry,
    RunPausedEvent,
    RunRenamedEvent,
    RunResumedEvent,
    RunStartedEvent,
    RunStartFailedEvent,
    RunStoppedEvent,
    StageChangedEvent,
    SummaryDataChangedEvent,
    TaskCompletedEvent,
    TaskFileChangedEvent,
    TaskRetryEvent,
    WorkspaceChangedEvent,
)
from ollama_llm_bench.backend.events.protocols import EventBus, Subscription

__all__: list[str] = [
    "SIGNAL_APP_READINESS_CHANGED",
    "SIGNAL_APP_SETTINGS_CHANGED",
    "SIGNAL_CHART_DATA_CHANGED",
    "SIGNAL_DETAILED_DATA_CHANGED",
    "SIGNAL_GLOBAL_MESSAGE",
    "SIGNAL_INFERENCE_ACTIVITY_CHANGED",
    "SIGNAL_INFERENCE_COMPLETED",
    "SIGNAL_INFERENCE_PROGRESS",
    "SIGNAL_INFERENCE_STARTED",
    "SIGNAL_JUDGE_COMPLETED",
    "SIGNAL_JUDGE_MODEL_EXCLUDED",
    "SIGNAL_JUDGE_STARTED",
    "SIGNAL_LOG_CLEARED",
    "SIGNAL_MODEL_STABILITY_CHANGED",
    "SIGNAL_MODEL_SWITCHED",
    "SIGNAL_PROGRESS_UPDATED",
    "SIGNAL_PROVIDER_INFERENCE_TEST_COMPLETED",
    "SIGNAL_PROVIDER_REGISTRY_RELOADED",
    "SIGNAL_PROVIDER_SWITCHED",
    "SIGNAL_RUN_ANALYSIS_RECEIVED",
    "SIGNAL_RUN_FAILED",
    "SIGNAL_RUN_FINISHED",
    "SIGNAL_RUN_ID_CHANGED",
    "SIGNAL_RUN_LIST_CHANGED",
    "SIGNAL_RUN_PAUSED",
    "SIGNAL_RUN_RENAMED",
    "SIGNAL_RUN_RESUMED",
    "SIGNAL_RUN_STARTED",
    "SIGNAL_RUN_START_FAILED",
    "SIGNAL_RUN_STOPPED",
    "SIGNAL_STAGE_CHANGED",
    "SIGNAL_SUMMARY_DATA_CHANGED",
    "SIGNAL_TASK_COMPLETED",
    "SIGNAL_TASK_FILE_CHANGED",
    "SIGNAL_TASK_RETRY",
    "SIGNAL_WORKSPACE_CHANGED",
    "AppReadinessChangedEvent",
    "AppSettingsChangedEvent",
    "ChartDataChangedEvent",
    "DetailedDataChangedEvent",
    "EventBus",
    "GlobalMessageEvent",
    "InferenceActivityChangedEvent",
    "InferenceCompletedEvent",
    "InferenceProgressEvent",
    "InferenceStartedEvent",
    "InferenceTestCompletedEvent",
    "JudgeCompletedEvent",
    "JudgeModelExcludedEvent",
    "JudgeStartedEvent",
    "LogClearedEvent",
    "ModelStabilityChangedEvent",
    "ModelSwitchedEvent",
    "ProgressUpdatedEvent",
    "ProviderHealthSummary",
    "ProviderRegistryReloadedEvent",
    "ProviderSwitchedEvent",
    "RunAnalysisReceivedEvent",
    "RunFailedEvent",
    "RunFinishedEvent",
    "RunIdChangedEvent",
    "RunListChangedEvent",
    "RunListEntry",
    "RunPausedEvent",
    "RunRenamedEvent",
    "RunResumedEvent",
    "RunStartFailedEvent",
    "RunStartedEvent",
    "RunStoppedEvent",
    "StageChangedEvent",
    "Subscription",
    "SummaryDataChangedEvent",
    "TaskCompletedEvent",
    "TaskFileChangedEvent",
    "TaskRetryEvent",
    "WorkspaceChangedEvent",
]
