"""Public surface for ``backend/infra/``: Clock, two-stream logging, path resolution.

Source of truth: ``docs/v3_specification/08_Cross_Cutting/08-E_interfaces_contracts.md``
§5 (Clock); ``docs/v3_specification/16_Engineering_Standards/06_LOGGING_STANDARD.md``
§§2-3, 6-7, 9; ``docs/v3_specification/10_Domain_and_Data/07_FILE_LAYOUT.md`` §8.1.
"""

from collections.abc import Iterator
from contextlib import contextmanager
import logging
from pathlib import Path

import icontract

from ollama_llm_bench.backend.infra._internal.clock import SystemClock
from ollama_llm_bench.backend.infra._internal.logging_setup import (
    DEFAULT_ROTATION_BACKUP_COUNT,
    DEFAULT_ROTATION_MAX_BYTES,
    configure_app_logging,
)
from ollama_llm_bench.backend.infra._internal.path_resolution import (
    app_log_dir,
    app_log_path,
    run_log_dir,
    run_log_path,
)
from ollama_llm_bench.backend.infra._internal.run_context import open_run_logger
from ollama_llm_bench.backend.infra.protocols import Clock, PlatformDetector

__all__: list[str] = [
    "app_log_dir",
    "app_log_path",
    "configure_logging",
    "make_system_clock",
    "open_run_log",
    "run_log_dir",
    "run_log_path",
]


@icontract.ensure(
    lambda result: result.now_utc() != "",
    "a freshly constructed Clock must always report a non-empty timestamp — a "
    "violation here means this factory's own wiring is broken, not that a caller "
    "passed bad input",
)
def make_system_clock() -> Clock:
    """Construct the default, real wall-clock ``Clock``.

    Returns:
        A ``Clock`` backed by the system clock and a monotonic counter.
    """
    return SystemClock()


@icontract.require(
    lambda level: (
        level in (logging.DEBUG, logging.INFO, logging.WARNING, logging.ERROR, logging.CRITICAL)
    ),
    "level must be one of the standard-library logging levels — this codebase's own "
    "call sites always pass one of the named constants, never an arbitrary int",
)
@icontract.require(
    lambda max_bytes: max_bytes > 0,
    "max_bytes is a fixed configuration constant this codebase supplies, not user "
    "input — it must be positive by construction",
)
@icontract.require(
    lambda backup_count: backup_count >= 0,
    "backup_count is a fixed configuration constant this codebase supplies, not user "
    "input — it must be non-negative by construction",
)
@icontract.ensure(
    lambda app_log_file: app_log_file.parent.is_dir(),
    "configure_logging must leave the app.log parent directory in place on disk",
)
def configure_logging(
    *,
    app_log_file: Path,
    level: int = logging.INFO,
    max_bytes: int = DEFAULT_ROTATION_MAX_BYTES,
    backup_count: int = DEFAULT_ROTATION_BACKUP_COUNT,
) -> None:
    """Install the one-time, two-stream ``structlog`` logging configuration.

    Configures the ``app.*`` namespace only: bound-context merge, level,
    ISO-8601 UTC timestamp, the ``redact_for_log`` processor, then render onto a
    non-blocking bounded queue drained by a single background writer thread onto
    a rotating ``app.log`` file handler. The ``run.*`` namespace is configured
    per run by ``open_run_logger`` and is never touched here.

    Idempotent: calling this twice in a test tears down the previously
    installed handler/listener pair first, so no handler is duplicated and no
    record is written twice. Performs no auto-configuration on import — it
    must be called explicitly, exactly once, from the composition root in
    later phases.

    Args:
        app_log_file: The destination path for the rotating application log,
            typically ``<app_data_root>/logs/app/app.log`` (see
            ``app_log_path``).
        level: The effective stdlib logging level for the ``app.*`` namespace
            (``INFO`` in a release build; ``DEBUG`` only for local debugging).
        max_bytes: The rotation trigger size in bytes (10 MB default per
            ``07_FILE_LAYOUT.md`` §8.1).
        backup_count: The number of rotated backups to retain (5 default).
    """
    configure_app_logging(
        app_log_file=app_log_file,
        level=level,
        max_bytes=max_bytes,
        backup_count=backup_count,
    )


@icontract.require(
    lambda run_id: len(run_id) > 0,
    "run_id is produced by this codebase's own RunsStore, never typed by a user — an "
    "empty value here is a bug in the caller",
)
@icontract.require(
    lambda correlation_id: len(correlation_id) > 0,
    "correlation_id is generated by this codebase's own run-start wiring, never "
    "user input — an empty value here is a bug in the caller",
)
@contextmanager
def open_run_log(
    *, platform_detector: PlatformDetector, run_id: str, correlation_id: str, unix_ts: int
) -> Iterator[logging.Logger]:
    """Open a run's dedicated, non-redacted, non-propagating logger.

    Convenience wrapper composing ``run_log_path`` with ``open_run_logger``;
    binds ``run_id``/``correlation_id`` via context variables for the scope of
    the returned context manager, so every record emitted within that scope —
    including from a worker thread started via a copied context — carries both
    fields, and closes the run's log file/handler on exit.

    Args:
        platform_detector: Supplies the resolved application-data root.
        run_id: The run identifier to bind and to name the log file after.
        correlation_id: The correlation identifier to bind for this run.
        unix_ts: The run's start time as a Unix timestamp in seconds, used in
            the log filename.

    Yields:
        The run-scoped ``DEBUG``-level logger.
    """
    log_file = run_log_path(platform_detector, run_id=run_id, unix_ts=unix_ts)
    with open_run_logger(
        run_id=run_id, correlation_id=correlation_id, run_log_file=log_file
    ) as run_logger:
        yield run_logger
