- task_id: "contextual_rule_application_007"
  category: "Text Processing"
  sub_category: "Contextual Replacement"
  question: |
    You are processing medical notes. If 'cancer' appears, replace it with '[REDACTED]'.
    If 'hypertension' appears, replace it with 'HTN'.
    NEVER alter other words.
    Input: 'Patient has stage 2 lung cancer and mild hypertension. No history of heart disease.'
  expected_answer:
    most_expected: "Patient has stage 2 lung [REDACTED] and mild HTN. No history of heart disease."
    good_answer: "Patient has stage 2 lung [REDACTED] & mild HTN. No history of heart disease."
    pass_option: "Any correct replacement of 'cancer' with '[REDACTED]' and 'hypertension' with 'HTN', no other changes."
  incorrect_direction: |
    Failure to replace 'cancer' or 'hypertension' correctly, altering other words, or adding new content.
